# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       gmime

# >> macros
# << macros
%define keepstatic 1

Summary:    Library for creating and parsing MIME messages
Version:    2.6.10
Release:    1
Group:      System/Libraries
License:    GPLv2+
URL:        http://spruce.sourceforge.net/gmime/
Source0:    http://download.gnome.org/sources/gmime/2.6/gmime-%{version}.tar.xz
Source1:    gpgme.m4
Source100:  gmime.yaml
Patch0:     gmime-2.5.8-gpg-error.patch
Patch1:     disable-gtkdoc.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0) >= 2.12.0
BuildRequires:  pkgconfig(zlib) >= 1.2.1.1
BuildRequires:  libgpg-error-devel
BuildRequires:  automake
BuildRequires:  libtool
BuildRequires:  gettext-devel

%description
The GMime suite provides a core library and set of utilities which may be
used for the creation and parsing of messages using the Multipurpose
Internet Mail Extension (MIME).


%package devel
Summary:    Header files to develop libgmime applications
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The GMime suite provides a core library and set of utilities which may be
used for the creation and parsing of messages using the Multipurpose
Internet Mail Extension (MIME). The devel-package contains header files
to develop applications that use libgmime.


%prep
%setup -q -n %{name}-%{version}/%{name}

# gmime-2.5.8-gpg-error.patch
%patch0 -p1
# disable-gtkdoc.patch
%patch1 -p1
# >> setup
%__cp $RPM_SOURCE_DIR/gpgme.m4 m4/
# << setup

%build
# >> build pre
AUTOGEN_SUBDIR_MODE=1 %autogen || true
# << build pre

%configure  \
    --disable-gtk-doc \
    --enable-cryptography=no \
    --program-prefix=%{name}

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
make install DESTDIR=$RPM_BUILD_ROOT
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_libdir}/lib*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc AUTHORS COPYING
%{_libdir}/lib*.a
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/gmime-*.pc
%{_includedir}/gmime-*
#%{_datadir}/gtk-doc/html/gmime-*
# << files devel
